apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: postgres
spec:
  sources:
    - name: products-api
      action: allow
  destination:
    name: postgres
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: deny-all
spec:
  sources:
    - name: '*'
      action: deny
  destination:
    name: '*'
